1- https://kibco.ac.ke/services/school-of-business-accountancy-and-languages/ 65k per sem
2- https://monrovia.kcau.ac.ke/course/certified-public-accountants-cpa/      16 k per sem
3- https://www.kenyaplex.com/colleges/1021-summit-institute-of-professionals.aspx
4- https://www.kenyaplex.com/colleges/2698-experts-business-college.aspx
5- https://www.kenyaplex.com/colleges/2599-traction-school-of-governance-and-business.aspx
5- https://www.kenyaplex.com/colleges/2672-juja-college-of-accountancy.aspx





ares to visit on monday
3 - KCA  UNIVERSITY  -- Muthaiga   knb
NIBS - OPPITE COOOPETIVE --no knb
4- Vision Institute of Professionals  Agrho House, 6th & 8th Floor, Moi Avenue.   - knb
-2 Summiut univetuy    ---Bank House, Moi Ave, Kenyatta Ave  --knb
- 1TRASTION UNIVESITY 5th floor, Pioneer House, Moi Avenue. Nairobi   ---- NEAR COOPERATIVE BANK  -knb
KIPS COLLEGE - OPPSITE COOPETIVE BANK  -----knb






Kenya Institute of Development Studies ---NEAR KENCOM no kncb
4 -Kenya Institute of Business and Counselling Studies (KIBCO) details  - Near Globe roundabout  -no knb
